server:
  port: 8001
spring:
  datasource:
    url: jdbc:oracle:thin:@10.211.55.7:1521:orcl
    username: IOMMS
    password: IOMMS
    driver-class-name: oracle.jdbc.driver.OracleDriver
mybatis:
  mapper-locations: classpath:mapper/*.xml